package com.automation;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

import io.github.bonigarcia.wdm.WebDriverManager;

public class TstNG_SoftAssertOrInstanceMthd_ {

	/* B. SoftAssert
	 * 
	 * "SoftAssert" is also called 'Instance MEthod'
	 * Create an Object/instance.
	 * 
	 * EVEN "ASSERTION FAILED" CONTUNUE with the REST of the PROGRAM 
	 * 
	 * */
	
	
	@Test
	
	public void test () throws Exception {
		SoftAssert softAssert = new SoftAssert();
		
		// Object/ Instance of "SoftAssert" is being CREATED
	
		WebDriver driver = null;
		
		softAssert.assertNotNull(driver);
		
		// 'driver' is 'null', softAssert.assertNotNull(driver); 
		// verified the given VALUE is NotNULL, 
		// So the SCRIPT SHOULD be "FAILED" but it SHOWS as PASS in CONSOLE
		
		// WHY?
		
		// Beacause, WHEN WE USE "SOFT ASSERT", EVENTHOUGH the TEST FAILED  
		// the REST of the Program will be EXECUTED and SHOWS the RESULT as PASS
		
		// Type in 'softAsse', ctlr space bar, Select "softAssert" then  
		// PUT a DOT, then type in 'assertN' hit ctrl space bar
		// select assertNotNull(Object,Object): void, pass the 'Object' value as 'driver'
		
		
		/*emailable-report.html
		 * 
		 * In the Above REPORT also EVENTHOUGH the SCRIPT FAILED, in the REPORT 
		 * it will be SHOWN as the SCRIPT is PASSED.  
		 * 
		 * WHY IT IS SHOWING LIKE THAT?
		 * 
		 * When you USE "SoftAssert" METHODS by the END of the PROGRAME(after driver.quit()), 
		 * DO NOT FORGET to WRITE "softAssert.assertAll();", 
		 * then only the FAILED MESSAGE will be RECORDED in the REPORT generated by "TestNG"
		 * and CONSOLE too,
		 * otherwise it will show as PASS ONLY
		 * 
		 * */


		WebDriverManager.chromedriver().setup();
		
		driver = new ChromeDriver();
		
		softAssert.assertNotNull(driver);
		
		// 'driver' is 'notnull', softAssert.assertNotNull(driver);  
		// verified that given VALUE is NotNULL, So the SCRIPT will be passed
				
		// Type in 'soft', ctlr space bar, softAssert, PUT a DOT, the type in 'assertN' hit ctrl space bar
		// select assertNotNull(Object,Object): void, pass the 'Object' value as 'driver'
		
		driver.manage().window().maximize();
		
		// driver.get("https://opensource-demo.orangehrmlive.com/index.php/pim/addEmployee");
		
		driver.get("https://www.thepancard.com/newpancard.php");
		
		Thread.sleep(2000);
		
		boolean actualValue = driver.findElement(By.id("rblCategory_0")).isSelected();
		
		// "isSelected()" method is to know the STATUS of the "RADIO BUTTON",
		// Store the VALUE in one VARIABLE which is "actualValue" 
		
		
		softAssert.assertTrue(actualValue);
		
		// 'boolean' returns True or false, the "actualValue"(radio button for 'Individual') 
		// on the APPLICATION BY DEFAULT should be SELECTED. 
		
		// softAssert.assertTrue(actualValue);, Verified that by default RADIO BUTTON was selected, 
		// so SCRIPT will be PASSED.
		
		
		Thread.sleep(2000);
		
		driver.quit();
		
		softAssert.assertAll();
		
	}

	
	
	
	
}
